# Generated by Django 2.2 on 2019-04-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190409_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='tag',
            field=models.ManyToManyField(related_name='manga', to='main.Tags'),
        ),
    ]
