# Generated by Django 2.2 on 2019-04-10 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190411_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='glava',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='main.Glava'),
        ),
    ]
