# Generated by Django 2.2 on 2019-04-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190411_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='datas',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='manga',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
