# Generated by Django 2.2 on 2019-04-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190412_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='datas',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
