# Generated by Django 2.2 on 2019-04-12 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_coments_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coments',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 15, 20, 39, 870702), verbose_name='Дата комментария'),
        ),
    ]
