# Generated by Django 2.1.8 on 2019-04-17 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190417_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coments',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 16, 27, 38, 970757), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='glava',
            name='numver',
            field=models.IntegerField(blank=True),
        ),
    ]
