# Generated by Django 2.1.8 on 2019-04-17 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190417_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coments',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 16, 28, 39, 101773), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='glava',
            name='numver',
            field=models.IntegerField(),
        ),
    ]
